version: '3'
services:

  bhugol:
    image: 'kartoza/geoserver:2.25.0'
    hostname: geoserver
    env_file:
      - ./.env
    container_name: ${BHUGOL_CONTAINER_NAME}
    volumes:
      - './bhugol/data/:/opt/geoserver/data_dir'
      - './bhugol/fonts/:/opt/fonts'
    ports:
      - ${EXPOSED_BHUGOL_PORT}:8080
    
    depends_on:
      - bhumi
    environment:
      - GEOSERVER_ADMIN_USER=${BHUGOL_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${BHUGOL_ADMIN_PASSWORD}
      - STABLE_EXTENSIONS=css-plugin,feature-pregeneralized-plugin 
      #- USE_DEFAULT_CREDENTIALS=true
    restart: on-failure
    networks:
      - bazra_network

  maarga:
    build: ./maarga
    image: ${MAARGA_IMAGE_NAME}
    container_name: ${MAARGA_CONTAINER_NAME}
    ports:
      - 5001:5000
    networks:
      - bazra_network

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.3
    ports:
      - 8090:8080
    environment:
      PBF_PATH: /data/selection.osm.pbf
      NOMINATIM_PASSWORD: very_secure_password
      # POSTGRES_HOST: bhumi
      # POSTGRES_DB: ${BHUMI_DATABASE_NAME}
      # POSTGRES_USER: ${BHUMI_USER}
      # POSTGRES_PASSWORD: ${BHUMI_PASSWORD}
    volumes:
      - ./pbf:/data  # Mount the local directory containing OSM PBF file
    shm_size: 1gb
    networks:
      - bazra_network

  bhumi:
    restart: on-failure
    image: kartoza/postgis:12.1
    env_file:
      - ./.env
    container_name: ${BHUMI_CONTAINER_NAME}
    ports:
      - ${EXPOSED_BHUMI_PORT}:5432
    volumes:
      - ./bhumi/data:/var/lib/postgresql/:rw
    environment:
      - POSTGRES_HOST=bhumi
      - POSTGRES_DB=${BHUMI_DATABASE_NAME}
      - POSTGRES_USER=${BHUMI_USER}
      - POSTGRES_PASSWORD=${BHUMI_PASSWORD}
      - POSTGRES_PORT=5432
      - ALLOW_IP_RANGE=0.0.0.0/0
    networks:
      - bazra_network
    
  imposm-worker:
    image: 'geotekne/imposm-worker:1.0.0'
    hostname: imposm-worker
    environment:
      - PARAMETERS=-i /pbf -c bhumi -v 12.1 -p 5432 -u ${BHUMI_USER} -w ${BHUMI_PASSWORD} -d ${BHUMI_DATABASE_NAME}
    volumes:
      - './pbf/:/pbf'
    depends_on:
      - bhumi
    networks:
      - bazra_network

networks:
  bazra_network:
    driver: bridge

